import { formatCurrency } from '@/lib/utils';
import { CategorySummary } from '@/hooks/useReports';

interface TaxReportProps {
    year: number;
    academyName: string;
    totals: {
        totalRevenue: number;
        totalExpense: number;
        netIncome: number;
    };
    categorySummaries: CategorySummary[];
}

export function TaxReport({ year, academyName, totals, categorySummaries }: TaxReportProps) {
    return (
        <div className="bg-white p-8 max-w-[210mm] mx-auto shadow-sm border border-slate-200 print:shadow-none print:border-none">
            <div className="text-center mb-8 border-b-2 border-slate-800 pb-4">
                <h1 className="text-2xl font-bold text-slate-900">{year}년도 간편장부 소득금액 요약표</h1>
                <p className="text-slate-500 mt-2">{academyName}</p>
            </div>

            <div className="space-y-6">
                {/* Income Summary */}
                <section>
                    <h3 className="text-lg font-bold text-slate-900 mb-3 border-b border-slate-300 pb-1">1. 총수입금액</h3>
                    <div className="flex justify-between items-center py-2 border-b border-slate-100">
                        <span className="font-medium text-slate-700">연간 매출액</span>
                        <span className="font-bold text-xl text-slate-900">{formatCurrency(totals.totalRevenue)}</span>
                    </div>
                </section>

                {/* Expense Summary */}
                <section>
                    <h3 className="text-lg font-bold text-slate-900 mb-3 border-b border-slate-300 pb-1">2. 필요경비</h3>
                    <table className="w-full text-sm text-left">
                        <thead className="bg-slate-50 border-y border-slate-200">
                            <tr>
                                <th className="px-4 py-2">계정과목</th>
                                <th className="px-4 py-2 text-right">금액</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-100">
                            {categorySummaries.map((cat) => (
                                <tr key={cat.id}>
                                    <td className="px-4 py-2 text-slate-700">{cat.name}</td>
                                    <td className="px-4 py-2 text-right font-medium text-slate-900">{formatCurrency(cat.amount)}</td>
                                </tr>
                            ))}
                            <tr className="bg-slate-50 font-bold border-t border-slate-300">
                                <td className="px-4 py-2 text-slate-900">필요경비 계</td>
                                <td className="px-4 py-2 text-right text-red-600">{formatCurrency(totals.totalExpense)}</td>
                            </tr>
                        </tbody>
                    </table>
                </section>

                {/* Net Income Summary */}
                <section className="bg-slate-50 p-6 rounded-lg border border-slate-200 mt-8">
                    <div className="flex justify-between items-center mb-2">
                        <span className="text-lg font-medium text-slate-700">총수입금액</span>
                        <span className="text-lg font-bold text-slate-900">{formatCurrency(totals.totalRevenue)}</span>
                    </div>
                    <div className="flex justify-between items-center mb-4 text-red-600">
                        <span className="text-lg font-medium">(-) 필요경비</span>
                        <span className="text-lg font-bold">{formatCurrency(totals.totalExpense)}</span>
                    </div>
                    <div className="border-t-2 border-slate-300 pt-4 flex justify-between items-center">
                        <span className="text-xl font-bold text-slate-900">소득금액 (예상)</span>
                        <span className="text-2xl font-bold text-blue-600">{formatCurrency(totals.netIncome)}</span>
                    </div>
                </section>

                <div className="mt-8 text-xs text-slate-400 text-center">
                    * 이 문서는 단순 참고용이며, 실제 세무 신고 시에는 증빙서류를 확인하시기 바랍니다.
                    <br />Generated by ITC Bookkeeping App
                </div>
            </div>
        </div>
    );
}
